//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmutLuckV1.Template.StudentTemplate {
    
    
    public partial class DailyEssayList {
        
        /// <summary>
        /// projectList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XmutLuckV1.Template.StudentTemplate.UserControl.NewestTopProjectWidget projectList;
        
        /// <summary>
        /// exercitationList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XmutLuckV1.Template.StudentTemplate.UserControl.NewestTopExercitationWidget exercitationList;
        
        /// <summary>
        /// actiList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XmutLuckV1.Template.StudentTemplate.UserControl.NewestTopActivityWidget actiList;
        
        /// <summary>
        /// prefessList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XmutLuckV1.Template.StudentTemplate.UserControl.NewestTopProfessionalWidget prefessList;
        
        /// <summary>
        /// dailyList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XmutLuckV1.Template.StudentTemplate.UserControl.DailyEssayList dailyList;
    }
}
