//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmutLuckV1.Template.StudentTemplate {
    
    
    public partial class Default {
        
        /// <summary>
        /// pjoList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XmutLuckV1.Template.StudentTemplate.UserControl.NewestTopProjectWidget pjoList;
        
        /// <summary>
        /// etwList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XmutLuckV1.Template.StudentTemplate.UserControl.NewestTopExercitationWidget etwList;
        
        /// <summary>
        /// atwList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XmutLuckV1.Template.StudentTemplate.UserControl.NewestTopActivityWidget atwList;
        
        /// <summary>
        /// pflList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XmutLuckV1.Template.StudentTemplate.UserControl.NewestTopProfessionalWidget pflList;
        
        /// <summary>
        /// dewList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XmutLuckV1.Template.StudentTemplate.UserControl.NewestTopDailyEssayWidget dewList;
    }
}
