//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmutLuckV1.Template.StudentTemplate {
    
    
    public partial class Project {
        
        /// <summary>
        /// projectjDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XmutLuckV1.Template.StudentTemplate.UserControl.ProjectDetailControl projectjDetail;
        
        /// <summary>
        /// pjList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XmutLuckV1.Template.StudentTemplate.UserControl.NewestTopProjectWidget pjList;
        
        /// <summary>
        /// extList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XmutLuckV1.Template.StudentTemplate.UserControl.NewestTopExercitationWidget extList;
        
        /// <summary>
        /// acvList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XmutLuckV1.Template.StudentTemplate.UserControl.NewestTopActivityWidget acvList;
        
        /// <summary>
        /// professList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XmutLuckV1.Template.StudentTemplate.UserControl.NewestTopProfessionalWidget professList;
        
        /// <summary>
        /// dailyList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XmutLuckV1.Template.StudentTemplate.UserControl.NewestTopDailyEssayWidget dailyList;
    }
}
